In [1]:
import pandas as pd
import numpy as np

---

In [3]:
df1 = pd.read_csv("Telco_customer_churn.csv")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [4]:
df2 = pd.read_csv("Telco_customer_churn_demographics.csv")
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer ID           7043 non-null   object
 1   Count                 7043 non-null   int64
 2   Gender                7043 non-null   object
 3   Age                   7043 non-null   int64
 4   Under 30              7043 non-null   object
 5   Senior Citizen        7043 non-null   object
 6   Married               7043 non-null   object
 7   Dependents            7043 non-null   object
 8   Number of Dependents  7043 non-null   int64
dtypes: int64(3), object(6)
memory usage: 495.3+ KB

In [6]:
df3 = pd.read_csv("Telco_customer_churn_location.csv")
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location ID  7043 non-null   object
 1   Customer ID  7043 non-null   object
 2   Count        7043 non-null   int64
 3   Country      7043 non-null   object
 4   State        7043 non-null   object
 5   City         7043 non-null   object
 6   Zip Code     7043 non-null   int64
 7   Lat Long     7043 non-null   object
 8   Latitude     7043 non-null   float64
 9   Longitude    7043 non-null   float64
dtypes: float64(2), int64(2), object(6)
memory usage: 550.4+ KB

In [7]:
df3.head(3)

,Location ID,Customer ID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude
0,OXCZEW7397,8779-QRDMV,1,United States,California,Los Angeles,90022,"34.02381, -118.156582",34.023810,-118.156582
1,FCCECI8494,7495-OOKFY,1,United States,California,Los Angeles,90063,"34.044271, -118.185237",34.044271,-118.185237
2,HEHUQY7254,1658-BYGOY,1,United States,California,Los Angeles,90065,"34.108833, -118.229715",34.108833,-118.229715

In [9]:
df4 = pd.read_csv("Telco_customer_churn_population.csv")
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1671 non-null   int64
 1   Zip Code    1671 non-null   int64
 2   Population  1671 non-null   object
dtypes: int64(2), object(1)
memory usage: 39.3+ KB

In [11]:
df4.head()

   ID  Zip Code Population
0   1     90001     54,492
1   2     90002     44,586
2   3     90003     58,198
3   4     90004     67,852
4   5     90005     43,019

In [10]:
df5 = pd.read_csv("Telco_customer_churn_services.csv")
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Service ID                         7043 non-null   object
 1   Customer ID                        7043 non-null   object
 2   Count                              7043 non-null   int64
 3   Quarter                            7043 non-null   object
 4   Referred a Friend                  7043 non-null   object
 5   Number of Referrals                7043 non-null   int64
 6   Tenure in Months                   7043 non-null   int64
 7   Offer                              3166 non-null   object
 8   Phone Service                      7043 non-null   object
 9   Avg Monthly Long Distance Charges  7043 non-null   float64
 10  Multiple Lines                     7043 non-null   object
 11  Internet Service                   7043 non-null   object
 12  Internet Type                      5517 non-null   object
 13  Avg Monthly GB Download            7043 non-null   int64
 14  Online Security                    7043 non-null   object
 15  Online Backup                      7043 non-null   object
 16  Device Protection Plan             7043 non-null   object
 17  Premium Tech Support               7043 non-null   object
 18  Streaming TV                       7043 non-null   object
 19  Streaming Movies                   7043 non-null   object
 20  Streaming Music                    7043 non-null   object
 21  Unlimited Data                     7043 non-null   object
 22  Contract                           7043 non-null   object
 23  Paperless Billing                  7043 non-null   object
 24  Payment Method                     7043 non-null   object
 25  Monthly Charge                     7043 non-null   float64
 26  Total Charges                      7043 non-null   float64
 27  Total Refunds                      7043 non-null   float64
 28  Total Extra Data Charges           7043 non-null   int64
 29  Total Long Distance Charges        7043 non-null   float64
 30  Total Revenue                      7043 non-null   float64
dtypes: float64(6), int64(5), object(20)
memory usage: 1.7+ MB

In [25]:
cols = list(df1.columns) + list(df2.columns) + list(df3.columns) + list(df4.columns) + list(df5.columns)

In [26]:
len(set(cols))

59

In [27]:
cols = list(set(cols))

In [28]:
cols.sort()

In [29]:
cols

['Age',
 'Avg Monthly GB Download',
 'Avg Monthly Long Distance Charges',
 'CLTV',
 'Churn Label',
 'Churn Reason',
 'Churn Score',
 'Churn Value',
 'City',
 'Contract',
 'Count',
 'Country',
 'Customer ID',
 'CustomerID',
 'Dependents',
 'Device Protection',
 'Device Protection Plan',
 'Gender',
 'ID',
 'Internet Service',
 'Internet Type',
 'Lat Long',
 'Latitude',
 'Location ID',
 'Longitude',
 'Married',
 'Monthly Charge',
 'Monthly Charges',
 'Multiple Lines',
 'Number of Dependents',
 'Number of Referrals',
 'Offer',
 'Online Backup',
 'Online Security',
 'Paperless Billing',
 'Partner',
 'Payment Method',
 'Phone Service',
 'Population',
 'Premium Tech Support',
 'Quarter',
 'Referred a Friend',
 'Senior Citizen',
 'Service ID',
 'State',
 'Streaming Movies',
 'Streaming Music',
 'Streaming TV',
 'Tech Support',
 'Tenure Months',
 'Tenure in Months',
 'Total Charges',
 'Total Extra Data Charges',
 'Total Long Distance Charges',
 'Total Refunds',
 'Total Revenue',
 'Under 30',
 'Unlimited Data',
 'Zip Code']